Repository extreme-todo/frontend, pull requests merged in 2023-11, with the labels that each got.

#45 Feature/44 할 일 목록 날짜 별 할 일 목록 기본 UI 구현하기
  fixture/mockTodoList.ts
  public/index.html
  src/App.tsx
  src/DB/indexed.ts
  src/atoms/TagAtom.tsx
  src/atoms/TypoAtom.tsx
  src/atoms/index.ts
  src/components/MainTodo.tsx
  src/components/Modal.tsx
  src/components/Setting.tsx
  src/components/TodoList.tsx
  src/components/Welcome.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useDraggableInPortal.ts
  src/molecules/TodoCard.tsx
  src/molecules/index.ts
  src/organisms/DateCard.tsx
  src/organisms/index.ts
  src/styles/Global.tsx
  src/test/components/Setting.test.tsx
  src/test/components/TodoList.test.tsx
  src/test/molecules/TodoCard.test.tsx
Labels: Feature, UI

#47 Feature/41 지금 할 일 로직 todo 상태 설계 및 로직 작성
  fixture/mockLocalStorage.ts
  src/App.tsx
  src/components/MainTodo.tsx
  src/hooks/index.ts
  src/hooks/useCurrentTodo.ts
  src/hooks/usePomodoro.tsx
  src/shared/constants.ts
  src/test/hooks/usePomodoro.test.tsx
Labels: Feature

#49 ReferenceError: indexedDB is not defined
  src/components/Modal.tsx
  src/components/TodoList.tsx
  src/shared/queries.ts
  src/test/DB/indexedCalc.spec.ts
  src/test/components/Modal.test.tsx
  src/test/components/TodoList.test.tsx
  src/test/components/Welcome.test.tsx
  src/test/molecules/TodoCard.test.tsx
Labels: BugFix
