Repository extreme-todo/frontend, pull requests merged in 2023-06, with the labels that each got.

#15 Feature/welcome
  .eslintrc.js
  fixture/mockLocalStorage.ts
  package-lock.json
  public/btn_google_signin_dark_normal_web.png
  public/icons/check.svg
  public/icons/close.svg
  public/icons/tooltip.svg
  public/index.html
  src/atoms/BtnAtom.tsx
  src/atoms/GoogleLoginAtom.tsx
  src/atoms/IconAtom.tsx
  src/atoms/SwitchAtom.tsx
  src/atoms/TagAtom.tsx
  src/atoms/TypoAtom.tsx
  src/atoms/index.ts
  src/components/Modal.tsx
  src/components/SettingModal.tsx
  src/components/Welcome.tsx
  src/components/index.ts
  src/index.tsx
  src/molecules/LogInToUnlock.tsx
  src/shared/apis.ts
  src/styles/Global.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/test/components/Modal.test.tsx
  src/test/components/Welcome.test.tsx
  yarn.lock
Labels: SetUp, Feature, UI

#16 Update : 테스트 파일 변경된 naming 수정
  src/components/SettingModal.tsx
  src/test/components/Modal.test.tsx
  src/test/components/Welcome.test.tsx
  src/test/hooks/useCheckLogin.test.ts
Labels: BugFix, Feature

#17 Feature/ranking Records(나의 기록 추이) 작업
  src/App.tsx
  src/atoms/CardAtom.tsx
  src/atoms/TypoAtom.tsx
  src/components/RankingAndRecords.tsx
  src/components/index.ts
  src/molecules/LogInToUnlock.tsx
  src/molecules/RecordCell.tsx
  src/molecules/Records.tsx
  src/molecules/index.ts
  src/shared/apis.ts
  src/shared/interfaces.ts
  src/styles/Global.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/test/components/LogInToUnlock.test.tsx
  src/test/components/RankingAndRecords.test.tsx
  src/test/components/Records.test.tsx
  src/test/molecules/Records.test.tsx
Labels: Feature, UI
