Repository extreme-todo/frontend, pull requests merged in 2024-07, with the labels that each got.

#106 Feature/102 modal 컴포넌트 수정
  src/components/AddTodo.tsx
  src/components/Modal.tsx
  src/molecules/CategoryInput.tsx
  src/shared/inputValidation.ts
Labels: BugFix, Feature

#109 Refactor/108 todolist 내부 코드 분할 하기
  src/DB/indexed.ts
  src/components/TodoList.tsx
  src/components/TodoList/dragHelper.ts
  src/components/TodoList/index.tsx
  src/components/TodoList/mockAddTodos.ts
  src/shared/apis.ts
Labels: Refactor

#116 Update : #110 줄 간 간격 제거 및 반응형 최적화
  src/components/Welcome.tsx
  src/styles/Global.tsx
Labels: UI

#117 Responsive/111 setting modal 반응형
  package-lock.json
  package.json
  src/atoms/GoogleLoginAtom.tsx
  src/atoms/IconAtom.tsx
  src/atoms/PopperAtom.tsx
  src/atoms/SwitchAtom.tsx
  src/atoms/index.ts
  src/components/AddTodo.tsx
  src/components/Modal.tsx
  src/components/Setting.tsx
  src/components/TodoCard/content/EditUI.tsx
  src/components/TodoCard/content/TodoUI.tsx
  src/components/TodoCard/index.tsx
  src/components/Welcome.tsx
  src/components/index.ts
  src/molecules/DayPickerUI.tsx
  src/molecules/NowCard.tsx
  src/molecules/index.ts
  src/organisms/CalendarInput.tsx
  src/organisms/DateCard.tsx
  src/organisms/index.ts
  src/shared/interfaces.ts
  src/styles/Global.tsx
  src/test/components/TodoCard.test.tsx
  src/test/organisms/CalendarInput.test.tsx
  yarn.lock
Labels: UI

#118 Responsive/112 todolist modal 반응형
  src/components/Modal.tsx
  src/components/TodoList.tsx
  src/molecules/NowCard.tsx
Labels: UI

#114 Responsive/113 현재 todo 화면 반응형 작업
  src/atoms/IconAtom.tsx
  src/atoms/ProgressButtonAtom.tsx
  src/components/MainTodo.tsx
  src/components/Modal.tsx
  src/molecules/Clock.tsx
  src/molecules/CurrentTodo.tsx
  src/molecules/ExtremeModeIndicator.tsx
  src/molecules/SideButtons.tsx
  src/organisms/CurrentTodoCard.tsx
  src/styles/Global.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: UI

#121 Responsive/115 ranking records 반응형 작업
  src/components/RankingAndRecords.tsx
  src/components/Welcome.tsx
  src/hooks/useIsMobile.ts
  src/molecules/CartegorySelector.tsx
  src/molecules/CurrentTodo.tsx
  src/molecules/RankingTexts.tsx
  src/molecules/RecordCell.tsx
  src/molecules/SideButtons.tsx
  src/organisms/Ranking.tsx
  src/organisms/Records.tsx
  src/shared/constants.ts
  src/styles/theme.ts
Labels: UI
