Repository extreme-todo/frontend, pull requests merged in 2024-06, with the labels that each got.

#86 Feature/85 indexeddb에 utc 작업하기
  src/DB/indexed.ts
  src/DB/indexedCalc.ts
  src/components/TodoList.tsx
  src/test/DB/indexedCalc.spec.ts
Labels: Feature

#88 Feature/87 delete UI 생성하기
  src/components/MainTodo.tsx
  src/components/TodoList.tsx
  src/molecules/NowCard.tsx
  src/molecules/TodoCard/content/TodoUI.tsx
  src/molecules/TodoCard/index.tsx
  src/shared/apis.ts
  src/styles/Global.tsx
  src/test/molecules/TodoCard.test.tsx
Labels: Feature

#90 Bugfix/84 마이너 이슈 수정
  src/components/TodoList.tsx
  src/hooks/useCurrentTodo.ts
  src/hooks/useExtremeMode.tsx
  src/hooks/useIsOnline.ts
  src/hooks/usePomodoro.tsx
  src/organisms/Ranking.tsx
  src/organisms/Records.tsx
  src/shared/apis.ts
Labels: BugFix, Feature

#91 Feature/89 todo module 만들기
  src/DB/indexed.ts
  src/components/Setting.tsx
  src/shared/apis.ts
  src/shared/timeUtils.ts
  src/shared/todoModule.ts
Labels: Feature

#93 92 재발급된 id token 처리하기
  src/App.tsx
  src/components/TodoList.tsx
  src/hooks/useCurrentTodo.ts
  src/shared/apis.ts
Labels: Feature

#100 Feature/99 useisonline 리펙토링
  src/hooks/useIsOnline.ts
  src/test/hooks/useIsOnline.test.ts
Labels: Refactor

#103 Feature/102 modal 컴포넌트 수정
  src/components/AddTodo.tsx
  src/components/MainTodo.tsx
  src/components/Modal.tsx
Labels: UI

#104 95 테스트 코드 깨지는 버그 수정
  src/components/Modal.tsx
  src/components/Setting.tsx
  src/hooks/useExtremeMode.tsx
  src/shared/apis.ts
  src/test/components/Setting.test.tsx
  src/test/organisms/Records.test.tsx
Labels: BugFix
