Repository extreme-todo/frontend, pull requests merged in 2024-08, with the labels that each got.

#124 Responsive/119 todoui 반응형
  package-lock.json
  package.json
  src/App.tsx
  src/components/MainTodo.tsx
  src/components/Modal.tsx
  src/components/RankingAndRecords.tsx
  src/components/TodoCard/content/TodoUI.tsx
  src/components/TodoCard/index.tsx
  src/components/TodoList.tsx
  src/components/TodoList/index.tsx
  src/components/Welcome.tsx
  src/hooks/useTouchSensor.tsx
  src/organisms/DateCard.tsx
  src/styles/Global.tsx
  yarn.lock
Labels: Feature, UI

#129 128 pomodoro modal 반응형
  src/components/Modal.tsx
  src/components/PomodoroTimeSetting.tsx
  src/components/TodoCard/content/EditUI.tsx
  src/components/TodoCard/content/TodoUI.tsx
  src/molecules/CategoryInput.tsx
  src/organisms/CalendarInput.tsx
  src/organisms/DateCard.tsx
Labels: UI

#130 BugFix : addTodo의 queryInvalidate 안 되는 부분 수정
  src/components/Modal.tsx
Labels: BugFix

#132 128 pomodoro modal 반응형
  package-lock.json
  package.json
  src/components/TodoList/index.tsx
  src/hooks/useIsMobile.ts
  src/organisms/DateCard.tsx
  src/organisms/index.ts
  src/test/components/Modal.test.tsx
  src/test/components/RankingAndRecords.test.tsx
  src/test/components/TodoCard.test.tsx
  src/test/components/Welcome.test.tsx
  src/test/organisms/CalendarInput.test.tsx
Labels: BugFix

#133 Feature/123 fe 배포 준비
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  fly.toml
  package-lock.json
  package.json
Labels: 🍀Release

#134 Update : #123 deploy 브랜치 변경
  .github/workflows/deploy.yml
Labels: 🍀Release

#136 Hotfix : #123 테스트 코드 오류 수정
  src/test/hooks/useExtremeMode.test.tsx
  src/test/organisms/Records.test.tsx
Labels: 🍀Release

#137 #123 테스트 코드 오류 수정
  src/test/hooks/useExtremeMode.test.tsx
  src/test/organisms/Records.test.tsx
Labels: 🍀Release

#138 Hotfix : #123 테스트 코드 오류 수정
  src/test/components/Setting.test.tsx
Labels: 🍀Release

#139 #123 테스트 코드 오류 수정
  src/test/components/Setting.test.tsx
Labels: 🍀Release

#140 배포 중 테스트 코드 에러 수정
  src/components/Setting.tsx
Labels: 🍀Release

#141 셋팅 모달 주석 처리된 부분 수정
  src/components/Setting.tsx
Labels: 🍀Release

#142 Hotfix : #123 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: 🍀Release

#143 Hotfix : #123 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: 🍀Release

#144 Hotfix : #123 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: 🍀Release

#145 #123 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: 🍀Release

#146 Update : #123 deploy단계에서 fail 뜬 부분 수정
  src/DB/indexed.ts
Labels: 🍀Release

#147 #123 deploy단계에서 fail 뜬 부분 수정
  src/DB/indexed.ts
Labels: 🍀Release

#148 Update : #123 에러나는 부분 주석처리
  src/DB/indexed.ts
Labels: 🍀Release

#149 #123 에러나는 부분 주석처리
  src/DB/indexed.ts
Labels: 🍀Release

#150 Update : #123 사용하지 않는 모듈 import 제거
  src/shared/apis.ts
Labels: 🍀Release

#151 #123 사용하지 않는 모듈 import 제거
  src/shared/apis.ts
Labels: 🍀Release

#152 Feature/123 fe 배포 준비
  .github/workflows/deploy.yml
  public/favicon.ico
  public/index.html
  src/shared/apis.ts
Labels: 🍀Release

#153 github action deploy 수정
  .github/workflows/deploy.yml
  public/favicon.ico
  public/index.html
  src/shared/apis.ts
Labels: 🍀Release

#154 Update : #123 파비콘 추가 및 이미지 명칭 수정
  public/favicon.ico
  public/icons/btnDown.svg
  public/icons/btnUp.svg
  public/index.html
  public/manifest.json
  src/components/PomodoroTimeSetting.tsx
Labels: 🍀Release

#155 파비콘 추가 및 이미지 명칭 수정
  public/favicon.ico
  public/icons/btnDown.svg
  public/icons/btnUp.svg
  public/index.html
  public/manifest.json
  src/components/PomodoroTimeSetting.tsx
Labels: 🍀Release

#158 Hotfix/157 usehandlelogin 컨텍스트 복구하기
  fixture/mockLocalStorage.ts
  src/App.tsx
  src/components/MainTodo.tsx
  src/components/RankingAndRecords.tsx
  src/components/Setting.tsx
  src/components/Welcome.tsx
  src/components/index.ts
  src/hooks/LoginContext.tsx
  src/hooks/index.ts
  src/hooks/useCheckLogin.ts
  src/hooks/useCurrentTodo.ts
  src/index.tsx
  src/shared/apis.ts
  src/test/components/AddTodo.test.tsx
  src/test/components/RankingAndRecords.test.tsx
  src/test/components/Setting.test.tsx
  src/test/components/Welcome.test.tsx
  src/test/hooks/LoginContext.test.tsx
  src/test/hooks/useCheckLogin.test.ts
  src/test/hooks/useExtremeMode.test.tsx
Labels: BugFix

#163 Hotifx/161 be timer api 리팩토링 반영 작업
  src/components/Setting.tsx
  src/hooks/useCurrentTodo.ts
  src/hooks/useExtremeMode.tsx
  src/hooks/usePomodoro.tsx
  src/organisms/Records.tsx
  src/shared/apis.ts
  src/test/components/Setting.test.tsx
Labels: BugFix

#164 Hotfix/159 배포 후 찾은 hot fix 해야 될 내용들
  src/hooks/useCurrentTodo.ts
  src/hooks/useExtremeMode.tsx
  src/hooks/usePomodoro.tsx
  src/molecules/RecordCell.tsx
  src/organisms/CurrentTodoCard.tsx
  src/organisms/Records.tsx
Labels: BugFix
