Repository extreme-todo/frontend, pull requests merged in 2025-01, with the labels that each got.

#187 Refactor/186 addtodo 모달에 사용되는 molecule organism 수정하기
  public/icon/tomato.svg
  src/atoms/IconAtom.tsx
  src/atoms/InputAtom.tsx
  src/atoms/PopperAtom.tsx
  src/atoms/TagAtom.tsx
  src/atoms/TomatoInput.tsx
  src/atoms/index.ts
  src/components/AddTodo.tsx
  src/components/Modal.tsx
  src/components/PomodoroTimeSetting.tsx
  src/components/RankingAndRecords.tsx
  src/components/Setting.tsx
  src/components/TodoCard/content/EditUI.tsx
  src/components/TodoCard/content/TodoUI.tsx
  src/components/Welcome.tsx
  src/hooks/LoginContext.tsx
  src/molecules/CategoryInput.tsx
  src/molecules/DayPickerUI.tsx
  src/molecules/LogInToUnlock.tsx
  src/molecules/NowCard.tsx
  src/molecules/RecordCell.tsx
  src/organisms/CalendarInput.tsx
  src/organisms/CurrentTodoCard.tsx
  src/organisms/Ranking.tsx
  src/shared/LoginEvent.ts
  src/shared/RandomTagColorList.ts
  src/shared/apis.ts
  src/styles/customPickerStyle.css
  src/styles/emotion.d.ts
  src/test/molecules/CategoryInput.test.tsx
  src/test/organisms/CalendarInput.test.tsx
Labels: Refactor, Feature, UI

#189 Refactor/188 현재 todo 화면 정리
  public/icons/bolt-red.svg
  public/icons/bolt.svg
  public/icons/pause-dark.svg
  public/logo.svg
  src/atoms/BtnAtom.tsx
  src/atoms/CardAtom.tsx
  src/atoms/IconAtom.tsx
  src/components/Welcome.tsx
  src/molecules/CategoryList.tsx
  src/molecules/Clock.tsx
  src/molecules/CurrentTodo.tsx
  src/molecules/ExtremeModeIndicator.tsx
  src/organisms/CurrentTodoCard.tsx
  src/styles/Global.tsx
  src/styles/theme.ts
Labels: Refactor, UI

#197 Refactor/196 todo UI 리팩토링
  public/icon/handle.svg
  public/icon/yellowHandle.svg
  public/icon/yellowTimer.svg
  public/icons/handle.svg
  src/atoms/IconAtom.tsx
  src/atoms/TagAtom.tsx
  src/components/TodoCard/content/TodoUI.tsx
  src/components/TodoCard/index.tsx
  src/components/TodoList/index.tsx
  src/hooks/useCurrentTodo.ts
  src/hooks/useEdit.tsx
  src/molecules/NowCard.tsx
  src/molecules/index.ts
  src/organisms/DateCard.tsx
  src/test/components/TodoCard.test.tsx
  src/test/organisms/NowCard.test.tsx
Labels: Refactor, UI

#193 180 휴식시간 디자인 수정
  README.md
  README/ccd398c3-be5a-4e47-9279-41aea1b29d26.png
  README/image 1.png
  README/image 2.png
  README/image 3.png
  README/image 4.png
  README/image 5.png
  README/image 6.png
  README/image 7.png
  README/image 8.png
  README/image.png
  public/icons/clock-red.svg
  public/icons/close-red.svg
  public/icons/close.svg
  public/icons/list-red.svg
  public/icons/tooltip-arrow.svg
  src/atoms/CardAnimationPlayer.tsx
  src/atoms/CardAtom.tsx
  src/atoms/TodoProgressBarAtom.tsx
  src/atoms/index.ts
  src/components/MainTodo.tsx
  src/hooks/useCurrentTodo.ts
  src/molecules/CategoryList.tsx
  src/molecules/Clock.tsx
  src/molecules/CurrentTodo.tsx
  src/molecules/ExtremeModeIndicator.tsx
  src/organisms/CurrentTodoCard.tsx
  src/organisms/RestCard.tsx
  src/styles/Global.tsx
  src/styles/cardAnimations.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: UI
